#ClusterRole for genie plugin
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: genie-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: genie-plugin
subjects:
  - kind: ServiceAccount
    name: genie-plugin
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: genie-policy
    namespace: {{ .Release.Namespace }}
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for genie policy controller
{{- if .Values.includePolicy }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: genie-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: genie-policy
subjects:
  - kind: ServiceAccount
    name: {{ .Values.geniePolicyLabel  }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---

